### ISSUE TITLE
Problem: Discrepancy b/n user docs & UI text for 'Use statement' field for ArchivesSpace DIP upload

### ISSUE THREAD

**Issue by currmie** [artefactual/archivematica-docs#106]
Version of the documentation: 1.7

Page (and section, if applicable) where the issue occurs: https://www.archivematica.org/en/docs/archivematica-1.7/user-manual/administer/dashboard-admin/#dashboard-as

Description of the issue:
Docs say the 'Use statement' field is required but the UI for AM 1.7 says otherwise.
Here's a screenshot of the area in the UI:
![screen shot 2018-03-23 at 11 45 38 am](https://user-images.githubusercontent.com/35077919/37848002-e60644fe-2e8f-11e8-84d6-8486c1de7bb9.png)

**Comment by currmie** [comment]
I briefly Slack-chatted with Ross and he said that in his testing, he never filled in that field and relied on the asterisks in the UI that was previously coded. Same goes for me in my testing so far-- DIP hasn't failed yet. Ross also suggested checking in with Ashley since she's been working with AS lately.

**Comment by sromkey** [comment]
It used to be required, but since it's not actually required by ASpace we changed the requirement. So it's an issue in the docs, not in the interface/functionality.
