### ISSUE TITLE
Enhancement: Remove trailing period in technical install instructions

### ISSUE THREAD

**Issue by ablwr** [artefactual/archivematica-docs#113]
Version of the documentation:
Instructions for using the archivematica-docs repo in the Wiki.

Page (and section, if applicable) where the issue occurs:
https://github.com/artefactual/archivematica-docs/wiki/Technical-details
Description of the issue:
I propose removing the trailing periods under the Editing Locally section of the Technical details page of the Wiki for this repository for instructions that end in code blocks. Although they are outside of the code block (in steps 1-4), it could still be confusing and people may accidentally copy-and-paste the entire line. I think removing the trailing periods provides more clarity and ease-of-use.

**Comment by sallain** [comment]
That's a great point. Agreed!
