### ISSUE TITLE
Problem: clamav-daemon needs to wait for the signature files after initial installation

### ISSUE THREAD

**Issue by mamedin** [artefactual/archivematica-docs#118]
Version of the documentation: 1.7

Page (and section, if applicable) where the issue occurs: 

Install Ubuntu: 12. Start the remaining services

Description of the issue: 

See https://github.com/artefactual/archivematica/issues/999

The clamav-daemon service needs the signature file created by clamav-freshclam to start. Sometimes it takes longer than 1 minute the first time clamav-freshclam is started. 

This is a Clamav issue, but this behaviour can be documented on archivematica-docs.

**Comment by mamedin** [comment]
On  the "Start the remaining services" section, we could move the Clamav services to its own subsection and mention that the `clamav-daemon` needs about 2 minutes after the `clamav-freshclam` service the first time it is started. 

The file`/var/lib/clamav/main.cvd` can be checked to determine whether the clamav-daemon service can be started safely.

**Comment by mamedin** [comment]
Hi, 


To solve this problem we could do the same thing that is done in the ``artefactual-labs/ansible-clamav`` role that makes use of the ``artefactual-labs/clamav-files`` repository:

https://github.com/artefactual-labs/ansible-clamav/blob/master/tasks/download-sigs.yml

RH/CentOS commands:

```
sudo -u root bash -c " \
wget -nv -P /var/lib/clamav https://github.com/artefactual-labs/clamav-files/raw/master/main.cvd
wget -nv -P /var/lib/clamav https://github.com/artefactual-labs/clamav-files/raw/master/daily.cvd
wget -nv -P /var/lib/clamav https://github.com/artefactual-labs/clamav-files/raw/master/bytecode.cvd
sudo chown clamupdate:clamupdate /var/lib/clamav/*cvd
";
```

Ubuntu commands:

```
sudo -u root bash -c " \
wget -nv -P /var/lib/clamav https://github.com/artefactual-labs/clamav-files/raw/master/main.cvd
wget -nv -P /var/lib/clamav https://github.com/artefactual-labs/clamav-files/raw/master/daily.cvd
wget -nv -P /var/lib/clamav https://github.com/artefactual-labs/clamav-files/raw/master/bytecode.cvd
sudo chown clamav:clamav /var/lib/clamav/*cvd
";
```

This procedure is idempotent: if these cvd files exist they are downloaded with the ``cvd.1`` extension:

ubuntu@mamedin-ffmpeg-ubuntu14:~$ sudo -u root bash -c " \
> wget -nv -P /var/lib/clamav https://github.com/artefactual-labs/clamav-files/raw/master/main.cvd
> wget -nv -P /var/lib/clamav https://github.com/artefactual-labs/clamav-files/raw/master/daily.cvd
> wget -nv -P /var/lib/clamav https://github.com/artefactual-labs/clamav-files/raw/master/bytecode.cvd
> sudo chown clamav:clamav /var/lib/clamav/*cvd
> ";
2018-04-26 18:43:30 URL:https://raw.githubusercontent.com/artefactual-labs/clamav-files/master/main.cvd [64720632/64720632] -> "/var/lib/clamav/main.cvd.1" [1]
2018-04-26 18:43:33 URL:https://raw.githubusercontent.com/artefactual-labs/clamav-files/master/daily.cvd [39494038/39494038] -> "/var/lib/clamav/daily.cvd.1" [1]
2018-04-26 18:43:33 URL:https://raw.githubusercontent.com/artefactual-labs/clamav-files/master/bytecode.cvd [78992/78992] -> "/var/lib/clamav/bytecode.cvd.1" [1]
```

**Comment by jhsimpson** [comment]
That seems like a good idea @mamedin - I suggest making it optional in the docs, the alternative is for the user just to wait an extra minute?

Just nitpicking, but technically, that is not idempotent - if the procedure was idempotent, it would result in the exact same files being download each time it is run.  If the 2nd time you run it, you have twice as many files, that is not idempotent.

**Comment by mamedin** [comment]
Yes, the freshclam takes 1 or 2 minutes to download the initial files.

About idempotency: Good catch, it is better to say: it is not dangerous when these files exist.
