### ISSUE TITLE
Problem: unclear audience for admin manual

### ISSUE THREAD

**Issue by sromkey** [artefactual/archivematica-docs#119]
Version of the documentation: All

Page (and section, if applicable) where the issue occurs: Index page and Installation page

Description of the issue:

Our recommended audience for the admin manual and particularly the installation instructions should be for systems administrators who are comfortable in the Linux environment. Currently the docs could mislead a person into thinking it's appropriate for archivists to be responsible for installing and maintaining Archivematica which I do not think is a realistic expectation.

**Comment by sallain** [comment]
Just some notes about places that audience is addressed. This is in reference to 1.7; some of these things may not have been cherry-picked back to earlier versions.

On the [index page](https://www.archivematica.org/docs/archivematica-1.7/) of the docs, the blurb under the Admin manual heading reads:
"The administrator manual is intended for systems administrators who are responsible for installing, configuring, setting up, and maintaining Archivematica and related systems."

On the [installation page](https://www.archivematica.org/en/docs/archivematica-1.7/admin-manual/installation-setup/installation/installation/#installation), the second paragraph under Overview reads:
"These instructions are designed to get you up and running as quickly as possible, even if you are not familiar the various tools and applications that are bundled into Archivematica. Experience with the Linux command line is helpful, and to support a running production system it should be considered a requirement."

I think we should strengthen these statements.

**Comment by ablwr** [comment]
I think the information on the index page of the docs are clear!

**Comment by sallain** [comment]
I think that this has been addressed in a few different ways in the past year, so I'm closing this issue - feel free to reopen!
