### ISSUE TITLE
Another Wrong Command in CentOS Installation Instructions

### ISSUE THREAD

**Issue by jpellman** [artefactual/archivematica-docs#121]
Version of the documentation: 1.7

Page (and section, if applicable) where the issue occurs: [CentOS Installation Instructions](https://www.archivematica.org/en/docs/archivematica-1.7/admin-manual/installation-setup/installation/install-centos/#install-pkg-centos), step 5, third bullet point

Description of the issue:

[Previous iterations of the 1.7 docs](https://www.archivematica.org/en/docs/archivematica-1.7/admin-manual/installation/installation/#install-pkg-centos) have included the following command for this step:

```
sudo -u archivematica bash -c " \
set -a -e -x
source /etc/sysconfig/archivematica-dashboard
cd /usr/share/archivematica/dashboard
/usr/share/python/archivematica-dashboard/bin/python manage.py migrate
";
```

The current iteration (post re-organization of the docs) includes the following command for this step:

```
sudo -u archivematica bash -c " \
set -a -e -x
source /etc/sysconfig/archivematica-dashboard
cd /usr/share/archivematica/dashboard
/usr/share/archivematica/virtualenvs/archivematica-dashboard/bin/python manage.py migrate
";
```

Which results in the following error:

```
[centos@ip-172-31-10-71 ~]$ sudo -u archivematica bash -c " \
> set -a -e -x
> source /etc/sysconfig/archivematica-dashboard
> cd /usr/share/archivematica/dashboard
> /usr/share/archivematica/virtualenvs/archivematica-dashboard/bin/python manage.py migrate
> ";
+ source /etc/sysconfig/archivematica-dashboard
++ ARCHIVEMATICA_DASHBOARD_DASHBOARD_DJANGO_SECRET_KEY=pZf2I02qNiNH7TyUzzPQCDv4lKZsi30F
++ ARCHIVEMATICA_DASHBOARD_DASHBOARD_DJANGO_ALLOWED_HOSTS='*'
++ AM_GUNICORN_BIND=127.0.0.1:7400
++ DJANGO_SETTINGS_MODULE=settings.production
++ ARCHIVEMATICA_DASHBOARD_DB_NAME=MCP
++ ARCHIVEMATICA_DASHBOARD_DB_USER=archivematica
++ ARCHIVEMATICA_DASHBOARD_DB_PASSWORD=demo
++ ARCHIVEMATICA_DASHBOARD_DB_HOST=localhost
++ ARCHIVEMATICA_DASHBOARD_DB_PORT=3306
++ ARCHIVEMATICA_DASHBOARD_GEARMAN=localhost:4730
++ ARCHIVEMATICA_DASHBOARD_ELASTICSEARCH=localhost:9200
++ PYTHONPATH=/usr/lib/archivematica/archivematicaCommon/:/usr/share/archivematica/dashboard
+ cd /usr/share/archivematica/dashboard
+ /usr/share/archivematica/virtualenvs/archivematica-dashboard/bin/python manage.py migrate
bash: line 3: /usr/share/archivematica/virtualenvs/archivematica-dashboard/bin/python: No such file or directory
```

The command from the older docs is the correct command and runs fine.

**Comment by sevein** [comment]
@jpellman I've realized that our docs were not asking users to install the development repos but the final repos instead. As a result, some of the new commands were not working because the packages being installed were too old.

I've just submitted a PR that should solve the problem: https://github.com/artefactual/archivematica-docs/pull/126.
