### ISSUE TITLE
"Administration" instead of "Administrators" in Step 2 of Post-Install Instructions

### ISSUE THREAD

**Issue by jpellman** [artefactual/archivematica-docs#127]
Version of the documentation: 1.7

Page (and section, if applicable) where the issue occurs: Step 2 of post-install instructions [here](https://www.archivematica.org/en/docs/archivematica-1.7/admin-manual/installation-setup/installation/install-centos/#centos-post-install-config) and [here](https://www.archivematica.org/en/docs/archivematica-1.7/admin-manual/installation-setup/installation/install-ubuntu/#ubuntu-post-install-config).

Description of the issue:

Minor typo- the storage service dashboard has an "Administration" tab.  Most reasonable people could figure out what to do but it would still be better if it read correctly / were consistent with the UI.  It might also be nice to bold/italicize otherwise distinguish menu options in the UI.

**Comment by ross-spencer** [comment]
Closed via main branch accidentally. We need to revert, and then merge from the dev branch for this issue.
