### ISSUE TITLE
Include pointers / primes for how to get the API key in the post-install instructions

### ISSUE THREAD

**Issue by jpellman** [artefactual/archivematica-docs#128]
Version of the documentation: 1.7

Page (and section, if applicable) where the issue occurs: Step 2 of post-install instructions [here](https://www.archivematica.org/en/docs/archivematica-1.7/admin-manual/installation-setup/installation/install-centos/#centos-post-install-config) and [here](https://www.archivematica.org/en/docs/archivematica-1.7/admin-manual/installation-setup/installation/install-ubuntu/#ubuntu-post-install-config).

Description of the issue:

At the end of step 2, it might be clearer to instruct an end-user that they need to click on 'Edit' next to the user they just created in order to get the API key at the bottom of the page.  I remember this not being immediately clear to me the first time I installed Archivematica.

**Comment by ross-spencer** [comment]
Closed via main branch accidentally. We need to revert, and then merge from the dev branch for this issue.
