### ISSUE TITLE
Problem: Dead links in Storage Service Docs don't conform to archives' community 404 best practice

### ISSUE THREAD

**Issue by ross-spencer** [artefactual/archivematica-docs#137]
**Version of the documentation:** Storage-service docs 0.10

**Page (and section, if applicable) where the issue occurs:**

* Link 1: https://www.archivematica.org/en/docs/storage-service-0.10/index/administrators/#administrators
* Link 2: https://www.archivematica.org/en/docs/storage-service-0.10/index/users/#users
* Found via: https://www.archivematica.org/en/docs/storage-service-0.10/index/

**Description of the issue:**

The two links should resolve but if we have the opportunity, the response to 404s shown below could be made friendlier in accordance with modern thinking about the effect of the error messages we return to users. See Laurent's post on 404s here: https://aranewprofessionals.wordpress.com/2017/05/05/why-404-errors-have-the-power-to-traumatise-nicola-laurent/ 

In this instance, we linked the user to these pages, so to say it is not what they were looking for is inaccurate. We can probably accept a bit more of the blame here, and maybe provide a link to these issue pages to report the issue if discovered and we think it's an error.

![image](https://user-images.githubusercontent.com/1880412/39181654-a5ac819a-47ba-11e8-8cf8-5930b8607e68.png)

**Comment by sallain** [comment]
I'd really like to see this improved, thanks for bringing it up @ross-spencer! 💖 I love the idea of linking to the issue page so that users can report a broken link. I did a bit of reading on the subject and the main suggestions for improving UX on 404 pages were: 1) provide context for the error, 2) provide a way to report the error, and 3) provide an alternate method for finding information.

A first pass at friendlier text:

Page not found
---
Sorry! This page was either deleted or it was moved to another location. [_# 1 ✓_]

Please consider reporting broken links through the [Archivematica documentation issue tracker](https://github.com/artefactual/archivematica-docs/issues). [_# 2 ✓_]

You can also search the documentation _(is there a good link for this?)_ or consult the documentation index _(is there a way to link to the most recent version of the docs?)_ to find what you were looking for. [_# 3 ✓_]

**Comment by ross-spencer** [comment]
This is cool - thanks @sallain! 

On three, I can't see an easy way to search, and I don't think we've got a way to link nicely to a #latest kind of tag. Not knowing the way we've configured the Artefactual web servers I couldn't tell you how easy it would be to do some nice redirects to a set of URLs that always pointed to our latest version of the docs, e.g. 1.6 right now... and 1.7 soon. But that certainly seems an option.

A good link for the docs in general might be the contents section:

AtoM: https://www.accesstomemory.org/en/docs/2.3/contents/
AM: https://www.archivematica.org/en/docs/archivematica-1.6/contents/
Storage Service: https://www.archivematica.org/en/docs/storage-service-0.10/contents/  

Did you see above the search boxes in both something called a 'General Index'?

AM: https://www.archivematica.org/en/docs/archivematica-1.6/genindex/
Storage Service: https://www.archivematica.org/en/docs/storage-service-0.10/genindex/

They're blank for those, but AtoM has a really nice General Index: https://www.accesstomemory.org/en/docs/2.3/genindex/

**Comment by sallain** [comment]
Re: the General Index, I filed a ticket about it being blank: #143 

Maybe @sevein has thoughts about creating latest-version redirects?

**Comment by sevein** [comment]
FYI these two work:
- https://archivematica.org/docs
- https://archivematica.org/docs/latest

Would that be enough?

**Comment by sallain** [comment]
*Insert The More You Know gif here*

Thanks sevein!

**Comment by sallain** [comment]
Updated suggested text:

Page not found
---
Sorry! This page was either deleted or it was moved to another location.

Please consider reporting broken links through the [Archivematica documentation issue tracker](https://github.com/artefactual/archivematica-docs/issues).

You can also search the documentation from the search bar on the [documentation homepage](https://archivematica.org/docs/latest) or consult the [general index](https://www.archivematica.org/en/docs/archivematica-1.7/genindex/) to find what you were looking for.

**Comment by sevein** [comment]
I think that'd be an easy fix. The archivematica-web repo isn't public yet though but @ross-spencer FYI you can find it in gitolite/gitweb.

We could have a 404 specific to the /docs section of the site but right now there's only one that applies to the whole archivematica.org domain. So @sallain you may want to reword your suggested text so it applies to both cases:
- Generic, e.g.: https://www.archivematica.org/page-that-was-never-created
- Docs, e.g.: https://www.archivematica.org/docs/archivematica-1.7/not-found

Unless we want have two different 404s which is also possible with a bit of extra dev work in the sphinxdoc Django app that is part of archivematica-web.

**Comment by sallain** [comment]
Good point, @sevein. There's not really a place to file bugs about the site itself, but I think it'd be a pretty rare occurrence? So receiving them on the docs issue tracker wouldn't be the worst situation, I think.

An attempt at making this more generic:

Page not found
---
Sorry! This page was either deleted or it was moved to another location.

Please consider reporting broken links through the [Archivematica documentation issue tracker](https://github.com/artefactual/archivematica-docs/issues) or by contacting [Artefactual](https://www.artefactual.com/contact/).

If you are looking for information in the Archivematica documentation, you can search using the search bar on the [documentation homepage](https://archivematica.org/docs/latest) or consult the [general index](https://www.archivematica.org/en/docs/archivematica-1.7/genindex/).

**Comment by sevein** [comment]
Ok, changed made.

https://www.archivematica.org/en/docs/archivematica-1.7/not-found/

**Comment by sallain** [comment]
Oh hey look at that! Thanks @sevein!

**Comment by sallain** [comment]
@ross-spencer Is @sevein's work sufficient to call this issue closed? Just clearing out my issue assignments/mentions :)

**Comment by ross-spencer** [comment]
@sallain @sevein I think so! (Sorry had thought this was all tied up neatly already :) ) Exceptional work both - I love that we are in a position to be able to turn this around so quickly!
