### ISSUE TITLE
Problem: website app doesn't recycle deleted doc pages

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica-docs#142]
**Version of the documentation:** 1.7

**Description of the issue:**

I did a quick search: `8001`. I wanted to know in how many places we're dealing with that subtle configuration default in RPM-based packages and how we could make that simpler. I received three results:

https://www.archivematica.org/en/docs/archivematica-1.7/search/?q=8001
> ![image](https://user-images.githubusercontent.com/606459/39267623-3509afd0-4882-11e8-84f0-48264daa1767.png)

The third link in that list is:

https://www.archivematica.org/en/docs/archivematica-1.7/admin-manual/installation/installation/

As far as I know that page should not exist - there is a new . Perhaps this is a bug in our archivematica-web app that does not clean up removed pages?

**Comment by sallain** [comment]
I also discovered this, while looking into an older issue that had been reopened. There are other pages that should've been deleted as well:

* https://www.archivematica.org/en/docs/archivematica-1.7/admin-manual/installation/customization/antivirus-admin/#antivirus-admin
* https://www.archivematica.org/en/docs/archivematica-1.7/admin-manual/installation/customization/#customization

There shouldn't be any pages at `admin-manual/installation/...`, they should all be at `admin-manual/installation-setup/...`

Those docs are out of date and not being actively maintained. This could easily cause confusion if people arrive at the docs through a Google search.

**Comment by sevein** [comment]
This seems to fixed now. I logged in the build server and I manually called `make clean` in the git working tree of the Sphinx local repo. In the long-term I think we want to add this extra step to our `update-docs` script.

**Comment by sallain** [comment]
Great, glad to hear it was an easy fix!
