### ISSUE TITLE
Problem: need to document MCPClient and MCPServer changes for Phase 2 Columbia work 

### ISSUE THREAD

**Issue by kellyannewithane** [artefactual/archivematica-docs#153]
Version of the documentation: 1.7.1

Page (and section, if applicable) where the issue occurs: 
[Customization](https://www.archivematica.org/en/docs/archivematica-1.7/admin-manual/installation-setup/customization/customization/) 
[Installation](https://www.archivematica.org/en/docs/archivematica-1.7/admin-manual/installation-setup/installation/installation/#installation) 
[Upgrading](https://www.archivematica.org/en/docs/archivematica-1.7/admin-manual/installation-setup/upgrading/upgrading/#upgrade)
[Customization and automation]( https://www.archivematica.org/en/docs/archivematica-1.7/admin-manual/installation-setup/customization/customization/#customization)

There may be other areas in the docs to update
[Wiki ](https://wiki.archivematica.org/MCP#MCP_Server)should also be updated

Description of the issue:
In order to improve performance, MCPClient has been changed to stop sending tool outputs (and possibly performance metrics) through the job scheduler, and instead write them directly to a document store. MCPServer has been changed to require only return code from client tasks. This needs to be described for users and for sysadmins when installing/upgrading

**Comment by jrwdunham** [comment]
We may want to update https://wiki.archivematica.org/MCPClient#Config_File with something like the following:

    For Archivematica 1.7 or newer please refer to https://github.com/artefactual/archivematica/tree/stable/1.7.x/src/MCPClient/install
