### ISSUE TITLE
CentOS: Firewalld not running on new install

### ISSUE THREAD

**Issue by mamedin** [artefactual/archivematica-docs#160]
Version of the documentation: 1.7

Page (and section, if applicable) where the issue occurs: 

install-centos/7. Finalizing installation

Description of the issue: 

This is not an archivematica issue, it is a CentOS issue, but I'm opening this issue in case it can help. On latest new CentOS installations, the firewalld is not running:

<pre>
[root@mamedin-centos-check-firewalld ~]# service firewalld status
Redirecting to /bin/systemctl status firewalld.service
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since lun 2018-05-14 09:52:39 UTC; 1s ago
     Docs: man:firewalld(1)
  Process: 11398 ExecStart=/usr/sbin/firewalld --nofork --nopid $FIREWALLD_ARGS (code=exited, status=0/SUCCESS)
 Main PID: 11398 (code=exited, status=0/SUCCESS)

may 14 09:52:38 mamedin-centos-check-firewalld systemd[1]: Starting firewalld - dynamic firewall daemon...
may 14 09:52:39 mamedin-centos-check-firewalld firewalld[11398]: ERROR: Exception DBusException: org.freedesktop.DBus.Error.AccessDenied: Connection ":1.20" is not allowed to own...ation file
may 14 09:52:39 mamedin-centos-check-firewalld systemd[1]: Started firewalld - dynamic firewall daemon.
Hint: Some lines were ellipsized, use -l to show in full.
</pre>

To fix this issue, I found several workarounds:

- Reboot VM or server
- restart the `dbus` service, and then restart the `firewalld` service
- Install firewalld before updating the complete system.

**Comment by sallain** [comment]
@mamedin is this still an issue that should be addressed?
