### ISSUE TITLE
Enhancement: Add note & commands to configure environmental variables for all deployment methods we support

### ISSUE THREAD

**Issue by currmie** [artefactual/archivematica-docs#162]
**Version of the documentation:** 1.7

**Page (and section, if applicable) where the issue occurs:**
Issue occurs in the install instructions for all deployment methods that we currently support.
For example: Ubuntu 16.04 (Xenial) installation instructions
URL: https://www.archivematica.org/en/docs/archivematica-1.7/admin-manual/installation-setup/installation/install-ubuntu/#install-pkg-ubuntu
Recommendation: Enhancement could go somewhere after or within step 9. A note similar to the one about running AM in indexless mode followed by the sample commands to issue would be helpful for new users.

**Description of the issue:**
The 'Task output capturing configuration' provides a nice overview of how Archivematica enable users to configure their MCP client(s) to control whether or not output streams from the client scripts are captured and then passed from the task workers to the task manager. However, when you get to the links and then click on your respective deployment method's installation instructions, the actual install. instructions do not specify HOW one actually sets this environmental variable.

**Comment by jrwdunham** [comment]
@currmie this may duplicate https://github.com/artefactual/archivematica-docs/issues/51.

**Comment by currmie** [comment]
@jrwdunham - thanks, looks like #51 would cover this issue
