### ISSUE TITLE
Problem: Sphinx linkcheck stalling part way through the process

### ISSUE THREAD

**Issue by ross-spencer** [artefactual/archivematica-docs#165]
**Version of the documentation:** 1.7 (latest build), Sphinx: `Sphinx (sphinx-build) 1.6.7`

**Page (and section, if applicable) where the issue occurs:** N/A

Description of the issue:

Trying to run `make linkcheck` the process gets part way through before pausing with no real indication of the issue. Verbosity is set to high:
```
ross-spencer@artefactual:~/git/artefactual/archivematica-docs:$ time make linkcheck
sphinx-build -b linkcheck -d _build/doctrees  -vvv -n . _build/linkcheck
```
Last portion of the output:
```
writing output... [ 35%] getting-started/other-resources/trac
[app] emitting event: 'doctree-resolved'(<document: <target...><section "trac review tool; trac"...>>, u'getting-started/other-resources/tra

(line   48) redirect  http://en.wikipedia.org/wiki/Responsibility_assignment_matrix - permanently to https://en.wikipedia.org/wiki/Responsibility_assignment_matrix
(line   32) redirect  http://public.ccsds.org/publications/archive/652x0m1.pdf - with Found to https://public.ccsds.org/Publications/Archive/652x0m1.pdf/default.aspx
(line  126) redirect  http://www.digitalpreservation.gov/ndsa/working_groups/standards.html - permanently to http://www.digitalpreservation.gov/ndsa/NDSAtoDLF.html
(line   10) broken    http://libraries.mit.edu/preservation/ - 404 Client Error: Not Found for url: https://libraries.mit.edu/preservation/
(line  122) redirect  https://groups.google.com/group/archivematica - with Found to https://groups.google.com/forum/#!forum/archivematica


(line   65) broken    http://206.191.128.204/trac/sites/default/files/SGDS%202009-9421%20%28D.%20BOUCON%29.pdf - HTTPConnectionPool(host='206.191.128.204', port=80): Max retries exceeded with url: /trac/sites/default/files/SGDS%202009-9421%20%28D.%20BOUCON%29.pdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f441dc4c2d0>: Failed to establish a new connection: [Errno 110] Connection timed out',))
```
I suspect a `linkcheck_timeout` might provide a suitable workaround for this, but cannot figure out how to supply it to the command, I have tried: `sphinx-build -b linkcheck -D linkcheck_timeout=3 -d _build/doctrees -n . _build/linkcheck`, this results in a `float is required` error when the links are checked.

**Comment by ross-spencer** [comment]
We can add something like this:
```
# -- Linkcheck --

linkcheck_timeout = 3
```
In the conf.py file and this looks to be honoured: https://github.com/artefactual/archivematica-docs/blob/c3e732b8a4d10e96efa6c0523f9062f55178e69f/conf.py

**Comment by ross-spencer** [comment]
And if we ignore the link before the stall:

`linkcheck_ignore = [r'http://206.191.128.204/trac/sites/default/files/SGDS%202009-9421%20%28D.%20BOUCON%29.pdf']`

There is no difference there either.

**Comment by sallain** [comment]
@ross-spencer this seems to have been resolved; closing this issue (reopen if I'm wrong!)
