### ISSUE TITLE
Problem: Add linkcheck to travis job

### ISSUE THREAD

**Issue by ross-spencer** [artefactual/archivematica-docs#169]
**Version of the documentation:** 1.7

**Page (and section, if applicable) where the issue occurs:** N/A

**Description of the issue:**

See #166. Currently the docs build will pass even if external links cannot be verified or are broken. Add the `make linkcheck` command to the travis.yml file to make sure that we check for this when building. 

https://github.com/artefactual/archivematica-docs/blob/c3e732b8a4d10e96efa6c0523f9062f55178e69f/.travis.yml

**Comment by sallain** [comment]
Replaced by archivematica/Issues#708
