### ISSUE TITLE
Problem: Storage service docs haven't a travis CI job

### ISSUE THREAD

**Issue by ross-spencer** [artefactual/archivematica-docs#170]
**Version of the documentation:** 0.11.x

**Page (and section, if applicable) where the issue occurs:** N/A

**Description of the issue:**

Currently the storage-service docs are not being build through travis ci which makes it harder to spot commits that might be broken for other users. If we add a travis-ci job for the storage service we can make sure we run through various checks, including, #169.

**Comment by ablwr** [comment]
According to [this issue and PR](https://github.com/archivematica/Issues/issues/190), this has been resolved so I am closing this issue. :tada:
