### ISSUE TITLE
Problem: the docs do not indicate that metadata can target objects/

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/archivematica-docs#172]
Version of the documentation: 1.7

Page (and section, if applicable) where the issue occurs: https://www.archivematica.org/en/docs/archivematica-1.7/user-manual/transfer/import-metadata/

Description of the issue: If your metadata.csv file contains a row whose `filename` value is `objects/`, then the metadata will appear in a `<mets:dmdSec>` that is linked to the `<mets:div>` element for the `objects/` directory. This should be made clear to readers of our documentation.

Here is an example transfer source directory:

    $ tree -C withmeta/
    withmeta/
    ├── file.txt
    └── metadata
        └── metadata.csv

    $ cat withmeta/metadata/metadata.csv
    filename,dc.title
    objects/,FOXPIGMONKEY

Here are the relevant bits of the resulting AIP:

    <mets:structMap ID="structMap_1" LABEL="Archivematica default" TYPE="physical">
        <mets:div LABEL="withmeta1-1ab6cece-9b30-45b0-8241-3fa99fc775b6" TYPE="Directory" DMDID="dmdSec_1">
            <mets:div LABEL="objects" TYPE="Directory" DMDID="dmdSec_2">

    <mets:dmdSec ID="dmdSec_2">
        <mets:mdWrap MDTYPE="DC">
            <mets:xmlData>
                <dcterms:dublincore xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xsi:schemaLocation="http://purl.org/dc/terms/ http://dublincore.org/schemas/xmls/qdc/2008/02/11/dcterms.xsd">
                    <dc:title>FOXPIGMONKEY</dc:title>
                </dcterms:dublincore>
            </mets:xmlData>
        </mets:mdWrap>
    </mets:dmdSec>

**Comment by kellyannewithane** [comment]
Hi @jrwdunham, just circling back around to this now.  

I kind of feel like the docs say exactly that - metadata can target objects/ - we talk about targeting simple objects and compound objects and explicitly state 'The dmdSecs are linked to their directories or files in the structMap.'

Thoughts?  Did you have a particular section from that page in mind?  Do you want more precise language? I bet you do

**Comment by kellyannewithane** [comment]
Hi @jrwdunham , @sallain just talked it out with me.  I'll add that metadata can be added at the directory level as well as at the object level.
