### ISSUE TITLE
Problem: docs do not reflect compound/simple objects in metadata.csv correctly 

### ISSUE THREAD

**Issue by sromkey** [artefactual/archivematica-docs#179]
Version of the documentation: all

Page (and section, if applicable) where the issue occurs: Import metadata

Description of the issue: The import metadata page implies that you must choose between having metadata for simple objects OR compound objects, but in reality you can use the metadata.csv file for a combination of the two.

**Comment by ablwr** [comment]
I did update the docs a bit, but this uncovered the above bug.

But for reference, here is the PR for cleaning up the transfer page more generally: https://github.com/artefactual/archivematica-docs/pull/241

**Comment by sallain** [comment]
This has been addressed via a few different PRs so I'm closing it!
