### ISSUE TITLE
update docs on how to install without elasticsearch

### ISSUE THREAD

**Issue by kellyannewithane** [artefactual/archivematica-docs#33]
Problem: Need to document in admin manual and other relevant places how to install Archivematica without ElasticSearch

**Comment by kellyannewithane** [comment]
1.8 branch with updated documentation is ready for review

**Comment by sallain** [comment]
I'm reasonably confident that this was completed and that the changes are still present in the current version of the 1.8 documentation, even though we've substantially changed the installation pages. The only page that does not contain Elasticsearch instructions is [Automated installation using Ansible](https://www.archivematica.org/en/docs/archivematica-1.8/admin-manual/installation-setup/installation/install-ansible/) - should the optional Elasticsearch information be included on this page?

@sevein pinging you, though I'm not sure if you're the right person to ask.

**Comment by sevein** [comment]
@sallain there are instructions here: https://github.com/artefactual-labs/ansible-archivematica-src/#disable-elasticsearch-use. Perhaps the docs should point to that README because it contains other useful information.

**Comment by sallain** [comment]
Thanks @sevein! I'll update the docs.

**Comment by sallain** [comment]
Documented and added to release notes
