### ISSUE TITLE
Problem: need 1.8 Archivematica docs on the website

### ISSUE THREAD

**Issue by kellyannewithane** [artefactual/archivematica-docs#35]
Columbia University Library would like to review changes to Archivematica documentation for 1.8 but it's not yet on our website (nor is 1.7).

Similar to how AtoM does their docs, it would be great to break up our docs so that we show the stable branch first, then docs in development and then legacy docs last.

Question: how difficult would it be to automate changes to the docs so that analysts don't have to ask sysadmins to do this work?

![screen shot 2017-10-18 at 11 54 52 am](https://user-images.githubusercontent.com/25352922/31737180-89036322-b3fb-11e7-84e9-3c4e677437b1.png)

**Comment by hakamine** [comment]
AM 1.7 and 1.8 docs are on archivematica.org now

**Comment by sevein** [comment]
@hakamine we need this to be automated. Pushes to the 1.8 branch should trigger the deployment update.

**Comment by hakamine** [comment]
Will work on this. 
@sevein IIRC some time ago we had had some setup for doing automatic building of something, probably in another repo (storage service or storage service docs?), but was discontinued for some reason, do you recall what was the problem?

**Comment by sevein** [comment]
Yeah I think that was in an old Jenkins server that was deleted.
Perhaps @scollazo knows more.

**Comment by hakamine** [comment]
@kellyannewithane @sevein I think this is working now. git pushes to the 1.6, 1.7, or 1.8 branches of this repository should trigger a build of the docs in the archivematica.org site, changes should be there in about 5 minutes. I will try to setup something similar for the Storage Service docs.

**Comment by sevein** [comment]
@hakamine I'm sorry this comes late but can we ensure that the process does not complete (i.e. doesn't deploy) changes if the docs don't build? I think this is particularly important because the editor pushes commits directly to the main branches. Can you confirm that a commit bringing breaking changes in Sphinx won't cause the website to go down or something similar?
