### ISSUE TITLE
Problem: create `latest` alias for Storage Service docs

### ISSUE THREAD

**Issue by sallain** [artefactual/archivematica-docs#39]
For the AtoM and Archivematica docs, we use a `latest` alias to control intersphinx mapping. We should create an alias for the Storage Service docs as well, so that no one has to remember to change [sphinxdoc-inventory.json](https://gist.github.com/qubot/2dd2f7f96e51121061d4) to point to the current version of the Storage Service docs every time a new version is released.

**Comment by ross-spencer** [comment]
Closed by the replacement issue https://github.com/archivematica/Issues/issues/1030

**Comment by sallain** [comment]
Haha thanks @ross-spencer, I meant to close this but it just slipped my mind!
