### ISSUE TITLE
Problem: it is not clear which environment variables are available or how to set them under various deployment scenarios

### ISSUE THREAD

**Issue by scollazo** [artefactual/archivematica-docs#51]
With 1.7, there are a lot of configuration options that can be set using environment variables.

We need document how to change them,  their names, goals and default values in the documentation.

**Comment by jrwdunham** [comment]
The following notes may be useful in closing this issue:


    Ubuntu package installs: output capturing configuration
    -------------------------------------------------------

    In order to disable output capturing on a package-based Archivematica
    installation on Ubuntu, you must modify the MCP client configuration file at
    ``/etc/default/archivematica-mcp-client`` so that it sets the
    ``ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CAPTURE_CLIENT_SCRIPT_OUTPUT`` environment
    variable to ``false``. One method for ding that is provided below.

    .. code:: bash

        sudo sh -c 'echo "ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CAPTURE_CLIENT_SCRIPT_OUTPUT=false" >> /etc/default/archivematica-mcp-client'

    Then, if the MCP client process is already running, restart it:

    .. code:: bash

        sudo service archivematica-mcp-client restart

    Otherwise, if it needs to be started, then start it:

    .. code:: bash

        sudo service archivematica-mcp-client start


    CentOS package installs: output capturing configuration
    -------------------------------------------------------

    In order to disable output capturing on a package-based Archivematica
    installation on CentOS, you must modify the MCP client configuration file at
    ``/etc/sysconfig/archivematica-mcp-client`` so that it sets the
    ``ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CAPTURE_CLIENT_SCRIPT_OUTPUT`` environment
    variable to ``false``. One method for ding that is provided below.

    .. code:: bash

        sudo sh -c 'echo "ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CAPTURE_CLIENT_SCRIPT_OUTPUT=false" >> /etc/sysconfig/archivematica-mcp-client'

    Then, if the MCP client process is already running, restart it:

    .. code:: bash

        sudo -u root systemctl restart archivematica-mcp-client

    Otherwise, if it needs to be started, then start it:

    .. code:: bash

        sudo -u root systemctl enable archivematica-mcp-client
        sudo -u root systemctl start archivematica-mcp-client


    Ubuntu Ansible-based installs: output capturing configuration
    -------------------------------------------------------------

    TODO


    Docker Compose-based installs: output capturing configuration
    -------------------------------------------------------------

    TODO: use the ``AM_CAPTURE_CLIENT_SCRIPT_OUTPUT`` local environment variable.
