### ISSUE TITLE
Problem: no docs exists for Processing Storage usage

### ISSUE THREAD

**Issue by joel-simpson** [artefactual/archivematica-docs#57]
In the Administration tab, there is a screen labelled "Processing Storage Usage". 
This page (administration/usage/) is not described in the documentation. 
I would expect to find a description on https://www.archivematica.org/en/docs/archivematica-1.6/admin-manual/installation/dashboard-config/#dashboard-config
(I checked documentation for 1.7 and 1.8 and didn't find any there either. Also worth noting I am testing on a Jisc QA environment but don't believe this is a jisc specific feature).

**Comment by sromkey** [comment]
You're correct Joel. It looks like a commit was missed when we made the 1.6 docs- it is in the 1.5 docs (https://www.archivematica.org/en/docs/archivematica-1.5/user-manual/administer/dashboard-admin/#dashboard-usage). I'll work on adding the commit, thank you!

**Comment by sallain** [comment]
This was added in at some point - I'm not going to go find the commit, though!
