### ISSUE TITLE
Problem: need to update ArchiveSpace docs to provide a better idea of expected behaviour

### ISSUE THREAD

**Issue by kellyannewithane** [artefactual/archivematica-docs#60]
Edit: Icons look consistent with docs again. @kellyannewithane and I spoke, and we're seeking to turn this ticket into one that can help elaborate on expected ArchivesSpace behaviour when using it in concert with Archivematica.

**Comment by sallain** [comment]
This would be a good thing for @currmie to do!

**Comment by kellyannewithane** [comment]
oh yes!  i'll add her

**Comment by ross-spencer** [comment]
@currmie let me know if I can help at all. The fixes related to this we're expecting to be deployed to the QA server. 

Primary issue was creating SIPs from the appraisal tab: https://github.com/artefactual/archivematica/issues/862 (we don't really document enough about what is needed, but that ticket should help).

Icons issue was here: https://github.com/artefactual/archivematica/issues/859

**Comment by currmie** [comment]
Thanks @ross-spencer, the links to related issues are helpful. Will take a closer look tomorrow while in the office.
