### ISSUE TITLE
Problem: doc changes for phase 1 CUL work in 1.8 branch

### ISSUE THREAD

**Issue by kellyannewithane** [artefactual/archivematica-docs#62]
Documentation for phase 1 Columbia work is in 1.8 branch.  If phase 1 work for Columbia is going to be included in 1.7 release we need to move those changes from 1.8 to 1.7

**Comment by jhsimpson** [comment]
This issue overlaps with https://github.com/artefactual/archivematica/issues/878 - I think we should close this one as a duplicate, since #878 includes this task.

**Comment by sromkey** [comment]
Closing this now since it is a duplicate
