### ISSUE TITLE
Problem: Improve API documentation inside AM-Docs

### ISSUE THREAD

**Issue by ross-spencer** [artefactual/archivematica-docs#81]
As a developer I would like a single, clear, access point to understand the capabilities of the Archivematica API, and Storage Service API. With potential overlap between the two mechanisms, this might be a single resource that describes both. This may also improve visibility of the APIs capabilities to the community and potentially increase its usage. This would bring with it other advantages. 

Current references to the API within the docs are here:

* https://www.archivematica.org/en/docs/archivematica-1.7/admin-manual/installation/dashboard-config/#admin-dashboard-rest
* https://www.archivematica.org/en/docs/archivematica-1.7/admin-manual/index/
* https://www.archivematica.org/en/docs/archivematica-1.7/user-manual/administer/dashboard-admin/#dashboard-rest
* https://www.archivematica.org/en/docs/archivematica-1.7/user-manual/ingest/ingest/#api
* https://www.archivematica.org/en/docs/archivematica-1.7/user-manual/index/
* https://www.archivematica.org/en/docs/archivematica-1.7/user-manual/ingest/ingest/#api
* https://www.archivematica.org/en/docs/archivematica-1.7/getting-started/quick-start/quick-start/
* https://www.archivematica.org/en/docs/archivematica-1.7/admin-manual/installation/installation/#post-install-config

**Format Policy Register (FPR) API**

* https://www.archivematica.org/en/docs/archivematica-1.7/user-manual/preservation/preservation-planning/

**Wiki Pages**

* https://wiki.archivematica.org/Archivematica_API
* https://wiki.archivematica.org/Storage_Service_API

There are two dead (#) anchor links here:

1) https://www.archivematica.org/en/docs/archivematica-1.7/admin-manual/index/
* https://www.archivematica.org/en/docs/archivematica-1.7/admin-manual/index/installation/dashboard-config/#rest-api

2) https://www.archivematica.org/en/docs/archivematica-1.7/user-manual/index/
* https://www.archivematica.org/en/docs/archivematica-1.7/user-manual/index/administer/dashboard-admin/#rest-api

**Storage service docs**

* https://www.archivematica.org/en/docs/storage-service-0.10/contents/

**Comment by radhikasundararaman24** [comment]
Hello: I'd like to pitch in and help the community with some documentation support. What kind of doc help are you looking for?

**Comment by sromkey** [comment]
@radhikasundararaman24 Thank you so much! We so appreciate it. I think @ross-spencer will take the lead and make a suggestion to you- he might be a few days before he's able to respond.

In the meantime, would you be able to sign and send us a copy of our [Contributor's Agreement](https://wiki.archivematica.org/Contributor_Agreement)?

**Comment by ross-spencer** [comment]
Related PR: https://github.com/artefactual/archivematica-storage-service/pull/370

**Comment by sallain** [comment]
@currmie tagged you in just as an FYI; feel free to close this if you feel like there is an equivalent issue somewhere else or if this is no longer relevant.
