### ISSUE TITLE
Problem: FPR docs aren't in main docs repo

### ISSUE THREAD

**Issue by sallain** [artefactual/archivematica-docs#86]
The Format Policy Registry documentation is located on a branch in the [archivematica-fpr-admin](https://github.com/artefactual/archivematica-fpr-admin) repo. It's hard to remember where it is, and it gets neglected. As it's just a single page, it would be trivial to move the FPR docs to the main documentation repo. This makes sense especially in light of [Archivematica #970](https://github.com/artefactual/archivematica/issues/970), Problem: FPR server should be decoupled from Archivematica.

**Comment by sromkey** [comment]
I agree- @sallain, since I’m working on updating the Pres Planning docs anyway do you want me to take this on and combine the two?

**Comment by sallain** [comment]
@sromkey Go for it!

**Comment by sallain** [comment]
@romkey this got done, right? Are there any remaining tasks to complete?

**Comment by romkey** [comment]
@sallain I don't think this is the @romkey you're looking for :-)

**Comment by sallain** [comment]
@romkey It is not! This is the issue with different Slack names vs Github names 😂 

@sromkey, see above!

**Comment by sromkey** [comment]
Haha, @romkey nice to meet you. Maybe we're long lost relatives! ;)

@sallain, not quite resolved. We resolved it in the 1.7 docs but need a PR from 1.6.1 and earlier because the situation with the FPR server is slightly different in those versions (not decoupled, only turned off).

**Comment by sallain** [comment]
@sromkey I've added the admonition back to 1.4, which is the earliest version of the docs available on the website. I don't think it's worth bothering with anything earlier. I didn't add anything to the FPR docs (https://github.com/artefactual/archivematica-fpr-server/tree/master/docs), as I believe that whole repo will be deleted eventually - let me know if this is incorrect.

**Comment by sromkey** [comment]
That sounds good. I don't know if the repo will be deleted to archived or what, but definitely no need to update them, the idea being that we just won't link them from the website anymore.
